### ISSUE TITLE
README里面的iOS 和 Mac的链接放反了

### ISSUE THREAD

**Issue by tasselx** [coderyi/MonkeyForMac#1]
![image](http://ww1.sinaimg.cn/large/7c00f1e1gw1ewtk6a1av1j20i502pq38.jpg)

**Comment by coderyi** [comment]
谢谢提醒

**Comment by tasselx** [comment]
@coderyi  :joy: 哈哈 我是强迫症 这个issue可以关了

**Comment by coderyi** [comment]
谢谢
